/*
 * Trabajo Práctico de Compiladores 2008.
 * Analizador Léxico.
 * Archivo: VAFN.java
 * Creado el 8 de noviembre de 2008, 08:09 PM
 */

package Vista;

import generacion.Automata;
import generacion.TablaTransicion;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 * Ventana que muestra y administra los Distintos Automatas del Programa.
 * @author  mrodas
 */
public class VAutomatas extends javax.swing.JInternalFrame {

    /** 
     * Constructor Principal
     */
    public VAutomatas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        CPestañas = new javax.swing.JTabbedPane();
        Pestaña1 = new javax.swing.JPanel();
        Contenedor1 = new javax.swing.JScrollPane();
        TTransicion = new javax.swing.JTable();
        Contenedor2 = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Vista.AplicacionAnalizadorLexico.class).getContext().getResourceMap(VAutomatas.class);
        setFrameIcon(resourceMap.getIcon("Form.frameIcon")); // NOI18N
        setName("Form"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        CPestañas.setAutoscrolls(true);
        CPestañas.setName("CPestañas"); // NOI18N

        Pestaña1.setName("Pestaña1"); // NOI18N

        Contenedor1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Contenedor1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        Contenedor1.setAutoscrolls(true);
        Contenedor1.setName("Contenedor1"); // NOI18N

        TTransicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TTransicion.setMaximumSize(new java.awt.Dimension(50, 100));
        TTransicion.setMinimumSize(new java.awt.Dimension(15, 10));
        TTransicion.setName("TTransicion"); // NOI18N
        TTransicion.setPreferredSize(new java.awt.Dimension(55, 30));
        TTransicion.setRowSelectionAllowed(false);
        TTransicion.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Contenedor1, org.jdesktop.beansbinding.ELProperty.create("0"), TTransicion, org.jdesktop.beansbinding.BeanProperty.create("autoResizeMode"), "R");
        bindingGroup.addBinding(binding);

        Contenedor1.setViewportView(TTransicion);
        TTransicion.getColumnModel().getColumn(0).setResizable(false);
        TTransicion.getColumnModel().getColumn(0).setPreferredWidth(57);
        TTransicion.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("TTransicion.columnModel.title0")); // NOI18N

        javax.swing.GroupLayout Pestaña1Layout = new javax.swing.GroupLayout(Pestaña1);
        Pestaña1.setLayout(Pestaña1Layout);
        Pestaña1Layout.setHorizontalGroup(
            Pestaña1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pestaña1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Contenedor1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        Pestaña1Layout.setVerticalGroup(
            Pestaña1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pestaña1Layout.createSequentialGroup()
                .addComponent(Contenedor1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        CPestañas.addTab(resourceMap.getString("Pestaña1.TabConstraints.tabTitle"), Pestaña1); // NOI18N

        Contenedor2.setName("Contenedor2"); // NOI18N
        CPestañas.addTab(resourceMap.getString("Contenedor2.TabConstraints.tabTitle"), Contenedor2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CPestañas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CPestañas, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

/*
 * Función para Completar la tabla de Transición cada vez que la ventana
 * correspondiente se Active.
 * @param evt
 */
private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    TablaTransicion tabla = AF.getTablaTransicion();
    TTransicion = new JTable(tabla);
    /* Configuración Necesaria para el Contenedor de la Tabla de Transicion */
    Contenedor1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    Contenedor1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
    Contenedor1.setAutoscrolls(true);
    Contenedor1.setViewportView(TTransicion);
    
    /* Configuración necesario para la Tabla de Transición */
    TTransicion.setRowHeight(15);
    TTransicion.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    TTransicion.getColumnModel().getColumn(0).setWidth(100);
    TTransicion.updateUI();
}//GEN-LAST:event_formInternalFrameActivated


    /**
     * Sección de Variables del Programa.
     */
    private Automata AF;

    /**
     * Getter del autómata.
     * @return El autómata asociado.
     */
    public Automata getAF() {
        return AF;
    }

    /**
     * Setter del autómata.
     * @param AF El nuevo autómata asociado.
     */
    public void setAF(Automata AF) {
        this.AF = AF;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane CPestañas;
    private javax.swing.JScrollPane Contenedor1;
    private javax.swing.JScrollPane Contenedor2;
    private javax.swing.JPanel Pestaña1;
    private javax.swing.JTable TTransicion;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
