/*
 * WPrincipal2.java
 *
 * Created on 8 de noviembre de 2008, 05:39 PM
 */

package Vista;

import org.jdesktop.application.Action;

/**
 *
 * @author  Marcelo
 */
public class VPrincipal extends javax.swing.JInternalFrame {

    /** Creates new form WPrincipal2 */
    public VPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        Datos = new javax.swing.JPanel();
        Clases = new javax.swing.JComboBox();
        TAlfabeto = new javax.swing.JLabel();
        FPersonalizado = new javax.swing.JTextField();
        TPersonalizado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TERegular = new javax.swing.JLabel();
        FERegular = new javax.swing.JTextField();
        Procesos = new javax.swing.JPanel();
        BAFN = new javax.swing.JButton();
        BAFD = new javax.swing.JButton();
        bAFDmin = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setName("Form"); // NOI18N

        Principal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Principal.setName("Principal"); // NOI18N

        Datos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Requeridos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12))); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Vista.AplicacionAnalizadorLexico.class).getContext().getResourceMap(VPrincipal.class);
        Datos.setFont(resourceMap.getFont("Datos.font")); // NOI18N
        Datos.setName("Datos"); // NOI18N

        Clases.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personalizado", "[A-Z]", "[a-z]", "[0-9]", "[A-Z a-z]", "[A-Z a-z 0-9]" }));
        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(Vista.AplicacionAnalizadorLexico.class).getContext().getActionMap(VPrincipal.class, this);
        Clases.setAction(actionMap.get("ManejarClases")); // NOI18N
        Clases.setKeySelectionManager(null);
        Clases.setName("Clases"); // NOI18N

        TAlfabeto.setBackground(resourceMap.getColor("TAlfabeto.background")); // NOI18N
        TAlfabeto.setFont(resourceMap.getFont("TAlfabeto.font")); // NOI18N
        TAlfabeto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TAlfabeto.setText(resourceMap.getString("TAlfabeto.text")); // NOI18N
        TAlfabeto.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("TAlfabeto.border.lineColor"), 2, true)); // NOI18N
        TAlfabeto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TAlfabeto.setInheritsPopupMenu(false);
        TAlfabeto.setName("TAlfabeto"); // NOI18N

        FPersonalizado.setMaximumSize(new java.awt.Dimension(5, 1));
        FPersonalizado.setMinimumSize(new java.awt.Dimension(2, 20));
        FPersonalizado.setName("FPersonalizado"); // NOI18N

        TPersonalizado.setFont(resourceMap.getFont("TPersonalizado.font")); // NOI18N
        TPersonalizado.setText(resourceMap.getString("TPersonalizado.text")); // NOI18N
        TPersonalizado.setName("TPersonalizado"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        TERegular.setFont(resourceMap.getFont("TERegular.font")); // NOI18N
        TERegular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TERegular.setText(resourceMap.getString("TERegular.text")); // NOI18N
        TERegular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        TERegular.setName("TERegular"); // NOI18N

        FERegular.setName("FERegular"); // NOI18N

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos);
        Datos.setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TERegular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TAlfabeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DatosLayout.createSequentialGroup()
                            .addComponent(Clases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(TPersonalizado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(FPersonalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FERegular, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addGap(163, 163, 163)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addComponent(TAlfabeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clases, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TPersonalizado)
                    .addComponent(FPersonalizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TERegular, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FERegular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        Procesos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Procesos del Análisis Léxico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12))); // NOI18N
        Procesos.setName("Procesos"); // NOI18N

        BAFN.setAction(actionMap.get("procesarAFN")); // NOI18N
        BAFN.setName("BAFN"); // NOI18N

        BAFD.setFont(resourceMap.getFont("BAFD.font")); // NOI18N
        BAFD.setText(resourceMap.getString("BAFD.text")); // NOI18N
        BAFD.setName("BAFD"); // NOI18N

        bAFDmin.setText(resourceMap.getString("bAFDmin.text")); // NOI18N
        bAFDmin.setName("bAFDmin"); // NOI18N

        javax.swing.GroupLayout ProcesosLayout = new javax.swing.GroupLayout(Procesos);
        Procesos.setLayout(ProcesosLayout);
        ProcesosLayout.setHorizontalGroup(
            ProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BAFD, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAFDmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProcesosLayout.setVerticalGroup(
            ProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAFDmin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAFD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(Procesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Procesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void procesarAFN() {
        VAFN miAFN = new VAFN();
        String titulo = new String("AFN para Proyecto: \"".concat(this.getTitle().concat("\"")));
        miAFN.setTitle(titulo);
        miAFN.setVisible(true);
        this.getDesktopPane().add(miAFN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        this.getDesktopPane().updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAFD;
    private javax.swing.JButton BAFN;
    private javax.swing.JComboBox Clases;
    private javax.swing.JPanel Datos;
    private javax.swing.JTextField FERegular;
    private javax.swing.JTextField FPersonalizado;
    private javax.swing.JPanel Principal;
    private javax.swing.JPanel Procesos;
    private javax.swing.JLabel TAlfabeto;
    private javax.swing.JLabel TERegular;
    private javax.swing.JLabel TPersonalizado;
    private javax.swing.JButton bAFDmin;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
